# Generated by Django 5.1 on 2024-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultora_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to='thumb_banner')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='fotos_obras')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_obra', models.CharField(max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('detalhes', models.TextField(blank=True, max_length=2000, null=True)),
                ('imagens', models.ManyToManyField(blank=True, related_name='foto_obra', to='consultora_app.foto')),
            ],
        ),
    ]
