# Generated by Django 5.1 on 2024-08-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultora_app', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logomarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='logomarca')),
            ],
        ),
    ]
