# Generated by Django 5.1 on 2025-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultora_app', '0006_logomarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='thumb_video',
            field=models.ImageField(blank=True, null=True, upload_to='thumb_video'),
        ),
    ]
